apiVersion: v1
kind: Pod
metadata:
  name: agnhost-busybox1-win
  namespace: default
  labels:
    app: MyApp
spec:
  nodeName: a-ms-2004-win-1
  containers:
  - image: "k8sprow.azurecr.io/kubernetes-e2e-test-images/agnhost:2.13"
    args:
      - netexec
      - --http-port=80
      - --udp-port=80
    imagePullPolicy: IfNotPresent
    name: netexec
  restartPolicy: Always
