apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-hostnet
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: True
      containers:
      - image: nginx:stable
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
      nodeSelector:
        kubernetes.io/os: linux
