apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-name: server
  name: server-c8mg7
  namespace: default
spec:
  containers:
  - args:
    - porter
    env:
    - name: SERVE_PORT_80
      value: foo
    image: k8s.gcr.io/e2e-test-images/agnhost:2.32
    imagePullPolicy: IfNotPresent
    name: server-container-80
    ports:
    - containerPort: 80
      name: serve-80
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /agnhost
        - connect
        - --protocol=tcp
        - --timeout=1s
        - 127.0.0.1:80
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5qwbv
      readOnly: true
  - args:
    - porter
    env:
    - name: SERVE_PORT_81
      value: foo
    image: k8s.gcr.io/e2e-test-images/agnhost:2.32
    imagePullPolicy: IfNotPresent
    name: server-container-81
    ports:
    - containerPort: 81
      name: serve-81
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /agnhost
        - connect
        - --protocol=tcp
        - --timeout=1s
        - 127.0.0.1:81
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5qwbv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: a-ms-2004-win-1
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5qwbv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
