apiVersion: v1
kind: Service
metadata:
  name: s-netpol-2993-z-c
  namespace: default
spec:
  clusterIP: 10.96.69.9
  clusterIPs:
  - 10.96.69.9
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service-port-tcp-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: service-port-udp-80
    port: 80
    protocol: UDP
    targetPort: 80
  - name: service-port-tcp-81
    port: 81
    protocol: TCP
    targetPort: 81
  - name: service-port-udp-81
    port: 81
    protocol: UDP
    targetPort: 81
  selector:
    pod-name: server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
